import type { Block, MathSyntax } from "../spec/schema.js";
import { emitInline, rgb, strLit } from "../compiler/escape.js";
import type { ThemeTokens } from "./types.js";

type HeaderBlock = Extract<Block, { type: "header" }>;
type FooterBlock = Extract<Block, { type: "footer" }>;

/** Bundled Hebrew fallback face, appended to every font list for RTL coverage. */
const HEBREW_FALLBACK = "David Libre";

/** A Typst font tuple with the Hebrew fallback appended. */
const fontList = (primary: string) => `(${strLit(primary)}, ${strLit(HEBREW_FALLBACK)})`;

function headerContent(t: ThemeTokens, h: HeaderBlock, math: MathSyntax): string {
  const bits: string[] = [];
  const logo = h.logo ?? t.logo;
  if (logo) bits.push(`image(${strLit(logo)}, height: 1.2em)`);
  if (h.text) bits.push(`text(weight: "bold")[${emitInline(h.text, math)}]`);
  const inner = bits.length === 2 ? `#${bits[0]} #h(1fr) #${bits[1]}` : bits.length ? `#${bits[0]}` : "";
  return `[#set text(size: ${t.size.small}, fill: ${rgb(t.color.muted)})\n${inner}\n#v(0.2em)\n#line(length: 100%, stroke: 0.5pt + ${rgb(t.color.border)})]`;
}

function footerContent(t: ThemeTokens, f: FooterBlock, math: MathSyntax): string {
  const left = f.text ? emitInline(f.text, math) : "";
  const right = f.pageNumbers ? `#context counter(page).display()` : "";
  const grid = `#grid(columns: (1fr, auto), [${left}], [${right}])`;
  return `[#set text(size: ${t.size.small}, fill: ${rgb(t.color.muted)})\n${grid}]`;
}

/**
 * Build the Typst preamble for a theme: page geometry, text defaults, heading
 * show-rules, table styling, and the `#callout` helper the compiler calls.
 * Page-level header/footer blocks (collected by the compiler) are injected here.
 */
export function themePreamble(
  t: ThemeTokens,
  page: { header?: HeaderBlock; footer?: FooterBlock; dir?: string; lang?: string; math?: MathSyntax },
): string {
  const dir = page.dir ?? t.dir;
  const lang = page.lang ?? t.lang;
  const math = page.math ?? "latex";

  const callouts = (Object.keys(t.color.callout) as (keyof typeof t.color.callout)[])
    .map((k) => `  ${k}: (bg: ${rgb(t.color.callout[k].bg)}, border: ${rgb(t.color.callout[k].border)}),`)
    .join("\n");

  const pageArgs = [
    `paper: "${t.page.paper}"`,
    `margin: ${t.page.margin}`,
    page.header ? `header: ${headerContent(t, page.header, math)}` : null,
    page.footer ? `footer: ${footerContent(t, page.footer, math)}` : null,
  ]
    .filter(Boolean)
    .join(",\n  ");

  return `// Generated by @agentsox/pdf-builder — do not edit by hand.
#set page(
  ${pageArgs}
)
#set text(
  font: ${fontList(t.fonts.body)},
  size: ${t.size.base},
  fill: ${rgb(t.color.text)},
  lang: "${lang}",
  dir: ${dir},
)
#set par(justify: true, leading: 0.7em)
#set heading(numbering: none)
#show heading: set text(font: ${fontList(t.fonts.heading)}, fill: ${rgb(t.color.text)})
#show heading.where(level: 1): set text(size: ${t.size.h1})
#show heading.where(level: 2): set text(size: ${t.size.h2})
#show heading.where(level: 3): set text(size: ${t.size.h3})
#show heading.where(level: 4): set text(size: ${t.size.h4})
#show raw: set text(font: ${fontList(t.fonts.mono)})
#set table(stroke: 0.5pt + ${rgb(t.color.border)}, inset: ${t.space.inset}, align: left + horizon)
#show table.cell.where(y: 0): set text(weight: "bold")

#let _callout_colors = (
${callouts}
)
#let callout(kind, title, body) = block(
  fill: _callout_colors.at(kind).bg,
  stroke: (left: 3pt + _callout_colors.at(kind).border),
  inset: ${t.space.inset},
  radius: 4pt,
  width: 100%,
)[
  #if title != none [#text(weight: "bold", fill: _callout_colors.at(kind).border)[#title]\\ ]
  #body
]
`;
}
